[mypy]
python_version = 3.11
strict = true
warn_return_any = true
warn_unused_configs = true

[mypy-faster_whisper.*]
ignore_missing_imports = true

[mypy-av.*]
ignore_missing_imports = true

[mypy-soundfile.*]
ignore_missing_imports = true

[mypy-cryptography.*]
ignore_missing_imports = true

[mypy-omnivoice.*]
ignore_missing_imports = true

[mypy-torch.*]
ignore_missing_imports = true
